[Page][Olana] Hackathons List
jrolana/cmsc127_final_project pull request #10
Opened 2024-05-22 01:27 UTC by jrolana

Note:
Created only dummy data for currently log in user will update after finishing user register/sign in page.

2024-05-22 03:03 UTC, ezerssss requested changes

2024-05-22 03:03 UTC, ezerssss commented on hackathons_list.php
> +    <title>Document</title>
change title

2024-05-22 03:03 UTC, ezerssss commented on hackathons_list.php
> +    $currentUserID = 2;
from session to right? pero like question lang ba para like on the same page di siya correcting or somethni GHAHAHAHA

2024-05-22 03:03 UTC, ezerssss commented on hackathons_list.php
> +                $hackathon_details = $conn->query($hackathon_sql);
can probably make this into a simpler one SQL query

```
SELECT * FROM hackathons WHERE hackathonsID IN (SELECT hackathonID FROM participates WHERE userID=currentUserID AND dateEnd > $currentDate)
```

maybe a little bit readable is:
```
$joinedHackathons_sql = SELECT hackathonID FROM participates WHERE userID=currentUserID AND dateEnd > $currentDate;

$hackathons = SELECT * FROM hackathons WHERE hackathonsID IN ($joinedHackathons_sql)
```

2024-05-22 03:03 UTC, ezerssss commented on hackathons_list.php
> +                                "<button>Submit a project</button>" .
change to a form lang para ready na siya for integration soon

2024-05-22 03:03 UTC, ezerssss commented on hackathons_list.php
> +                $availHackathonID = $availHackathon["hackathonID"];
i think same sa previous ko na comment nga better if

```
$joinedHackathons_sql = SELECT hackathonID FROM participates WHERE userID=currentUserID;

$hackathons = SELECT * FROM hackathons WHERE hackathonsID NOT IN ($joinedHackathons_sql)
```

2024-05-22 03:03 UTC, ezerssss commented on hackathons_list.php
> +                                "<button>Join</button>" .
make into form

2024-05-22 03:03 UTC, ezerssss commented on scratch.txt
delete non final files in PR

2024-05-22 03:03 UTC, ezerssss commented on hackathons_list.php
> +                        if ($hackathon["dateEnd"] < $currentDate) {
ohhh here mo linagay ang if statement, better siguro if sa actual SQL ang checking para smaller rows ang makuha niya

```
$pastJoinedHackathons_sql = SELECT hackathonID FROM participates WHERE userID=currentUserID AND dateEnd <= $currentDate;

$hackathons = SELECT * FROM hackathons WHERE hackathonsID IN ($joinedHackathons_sql)
```

2024-05-22 03:06 UTC, jrolana commented on hackathons_list.php
> +    $currentUserID = 2;
yes for session

2024-05-22 03:50 UTC, ezerssss commented
maybe also change ang name ng php to `home.php` kay siya man ang home page

2024-05-26 02:41 UTC, ezerssss approved these changes

2024-05-26 02:42 UTC, merged